xCoords_right:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.00010259173129645305
- 0.00041020052102244686
- 0.0009223274265961756
- 0.0016381417763040307
- 0.0025564825166531358
- 0.0036758600956044163
- 0.004994458878631411
- 0.006510140093686098
- 0.008220445300295032
- 0.01012260037715873
- 0.012213520021786634
- 0.014489812754868964
- 0.0169477864212685
- 0.019583454178709978
- 0.022392540964452465
- 0.02537049042945709
- 0.028512472328801705
- 0.031813390356355706
- 0.035267890411007474
- 0.03887036928103568
- 0.0426149837325394
- 0.04649565998718479
- 0.05050610357389565
- 0.054639809538508805
- 0.05889007299483316
- 0.06324999999999997
- 0.06771251873646328
- 0.07227039098251369
- 0.07691622385270051
- 0.08164248178911923
- 0.08644149878411372
- 0.09130549081456873
- 0.09622656846762395
- 0.1011967497373304
- 0.10620797297149331
- 0.11125210994770163
- 0.11632097905733418
- 0.12140635857615899
- 0.1265
- 0.1315
- 0.1365
- 0.14150000000000001
- 0.1465
- 0.1515
- 0.1565
- 0.1615
- 0.1665
- 0.17149999999999999
- 0.1765
- 0.1815
- 0.1865
- 0.1915
- 0.1965
- 0.2015
- 0.20650000000000002
- 0.21150000000000002
- 0.2165
yCoords_right:
- -0.3
- -0.295
- -0.29
- -0.285
- -0.27999999999999997
- -0.275
- -0.27
- -0.265
- -0.26
- -0.255
- -0.25
- -0.245
- -0.24
- -0.235
- -0.22999999999999998
- -0.225
- -0.22
- -0.215
- -0.21000000000000002
- -0.20500000000000002
- -0.2
- -0.195
- -0.19
- -0.185
- -0.18
- -0.175
- -0.17
- -0.165
- -0.16
- -0.155
- -0.15000000000000002
- -0.14500000000000002
- -0.14
- -0.135
- -0.13
- -0.12500000000000003
- -0.12000000000000002
- -0.11500000000000002
- -0.11000000000000001
- -0.10500000000000001
- -0.09999999999999999
- -0.09490635857615899
- -0.08982097905733416
- -0.08475210994770163
- -0.0797079729714933
- -0.07469674973733037
- -0.06972656846762396
- -0.06480549081456873
- -0.059941498784113735
- -0.05514248178911922
- -0.0504162238527005
- -0.04577039098251367
- -0.04121251873646327
- -0.03675000000000002
- -0.03239007299483315
- -0.028139809538508795
- -0.024006103573895682
- -0.019995659987184777
- -0.016114983732539417
- -0.012370369281035673
- -0.008767890411007465
- -0.005313390356355738
- -0.0020124723288016955
- 0.0011295095705428776
- 0.004107459035547545
- 0.006916545821290032
- 0.00955221357873147
- 0.012010187245131046
- 0.014286479978213376
- 0.016377399622841265
- 0.018279554699704978
- 0.019989859906313898
- 0.0215055411213686
- 0.02282413990439558
- 0.02394351748334686
- 0.024861858223695965
- 0.02557767257340382
- 0.02608979947897755
- 0.026397408268703543
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
- 0.026499999999999996
tangentAngle_right:
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5506579123488058
- 1.510381083456632
- 1.4701042545644551
- 1.4298274256722778
- 1.3895505967801018
- 1.3492737678879234
- 1.308996938995747
- 1.268720110103569
- 1.2284432812113955
- 1.1881664523192184
- 1.1478896234270377
- 1.1076127945348617
- 1.0673359656426882
- 1.0270591367505078
- 0.9867823078583335
- 0.9465054789661564
- 0.9062286500739771
- 0.8659518211818027
- 0.8256749922896245
- 0.7853981633974483
- 0.7451213345052699
- 0.7048445056130966
- 0.6645676767209181
- 0.624290847828742
- 0.5840140189365631
- 0.5437371900443875
- 0.5034603611522103
- 0.4631835322600344
- 0.4229067033678565
- 0.3826298744756814
- 0.3423530455835
- 0.30207621669132906
- 0.2617993877991477
- 0.22152255890697198
- 0.18124573001479527
- 0.14096890112261912
- 0.10069207223044097
- 0.06041524333826488
- 0.020138414446090824
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
curvature_right:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- -7.905138339920948
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
