xCoords:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 5.5429830792458334e-05
- 0.00022169219322598632
- 0.0004987057107476434
- 0.0008863348000250071
- 0.0013843897373067848
- 0.001992626751282589
- 0.0027107481423960522
- 0.0035384024285526616
- 0.004475184517151648
- 0.005520635903357218
- 0.006674244894512016
- 0.007935446860583562
- 0.009303624510520414
- 0.010778108194383268
- 0.012358176231102747
- 0.01404305526170388
- 0.015831920627823987
- 0.01772389677533906
- 0.01971805768290047
- 0.021813427315173356
- 0.02400898010055358
- 0.02630364143313041
- 0.02869628819864878
- 0.031185749324213752
- 0.03377080635146795
- 0.0364501940329624
- 0.03922260095142718
- 0.04208667016164047
- 0.04504099985458054
- 0.04808414404353681
- 0.05121461327184279
- 0.054430875341885926
- 0.05773135606503649
- 0.06111444003212857
- 0.06457847140411724
- 0.06812175472252288
- 0.07174255573926794
- 0.0754391022654986
- 0.07920958503897685
- 0.0830521586096174
- 0.08696494224273757
- 0.09094602083957601
- 0.09499344587463177
- 0.09910523634936319
- 0.10327937976178113
- 0.1075138330914613
- 0.11180652379949363
- 0.11615535084287963
- 0.1205581857028804
- 0.1250128734268135
- 0.1295172336827869
- 0.13406906182685524
- 0.1386661299820752
- 0.1433061881289326
- 0.1479869652066067
- 0.15270617022453342
- 0.15746149338372262
- 0.1622506072072818
- 0.16707116767959176
- 0.17192081539357687
- 0.1767971767055092
- 0.18169786489678036
- 0.18662048134207282
- 0.19156261668335905
- 0.19652185200915362
- 0.20149576003844144
- 0.20648190630870195
- 0.21147785036744898
- 0.21648114696670168
yCoords:
- -0.3
- -0.295
- -0.29
- -0.285
- -0.27999999999999997
- -0.275
- -0.27
- -0.265
- -0.26
- -0.255
- -0.25
- -0.245
- -0.24
- -0.235
- -0.22999999999999998
- -0.225
- -0.22
- -0.215
- -0.21000000000000002
- -0.20500000000000002
- -0.2
- -0.195
- -0.19
- -0.185
- -0.18
- -0.175
- -0.17
- -0.165
- -0.16
- -0.155
- -0.15000000000000002
- -0.14500000000000002
- -0.14
- -0.135
- -0.13
- -0.12500000000000003
- -0.12000000000000002
- -0.11500000000000002
- -0.11000000000000001
- -0.10500000000000001
- -0.09999999999999998
- -0.09498934725980315
- -0.0899811469667017
- -0.08497785036744898
- -0.07998190630870186
- -0.07499576003844136
- -0.07002185200915359
- -0.065062616683359
- -0.0601204813420728
- -0.05519786489678035
- -0.0502971767055092
- -0.04542081539357678
- -0.04057116767959168
- -0.035750607207281765
- -0.03096149338372256
- -0.02620617022453338
- -0.021486965206606715
- -0.0168061881289326
- -0.01216612998207521
- -0.007569061826855156
- -0.003017233682786849
- 0.0014871265731865452
- 0.005941814297119638
- 0.010344649157120411
- 0.0146934762005064
- 0.01898616690853873
- 0.023220620238218914
- 0.027394763650636866
- 0.031506554125368263
- 0.03555397916042402
- 0.03953505775726249
- 0.04344784139038263
- 0.04729041496102318
- 0.051060897734501426
- 0.05475744426073209
- 0.05837824527747715
- 0.06192152859588279
- 0.06538555996787146
- 0.06876864393496354
- 0.07206912465811408
- 0.07528538672815724
- 0.07841585595646322
- 0.08145900014541949
- 0.08441332983835956
- 0.08727739904857282
- 0.09004980596703763
- 0.09272919364853208
- 0.09531425067578625
- 0.09780371180135122
- 0.10019635856686959
- 0.10249101989944645
- 0.10468657268482667
- 0.10678194231709956
- 0.10877610322466094
- 0.11066807937217601
- 0.11245694473829612
- 0.11414182376889728
- 0.11572189180561676
- 0.11719637548947959
- 0.11856455313941647
- 0.11982575510548799
- 0.12097936409664278
- 0.12202481548284835
- 0.12296159757144734
- 0.12378925185760398
- 0.12450737324871741
- 0.12511561026269324
- 0.125613665199975
- 0.12600129428925236
- 0.12627830780677402
tangentAngle:
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5707963267948966
- 1.5597343808315522
- 1.5376104889048618
- 1.515486596978178
- 1.493362705051484
- 1.4712388131247953
- 1.449114921198113
- 1.4269910292714174
- 1.4048671373447308
- 1.3827432454180464
- 1.36061935349135
- 1.3384954615646687
- 1.3163715696379759
- 1.2942476777112886
- 1.272123785784596
- 1.2499998938579095
- 1.2278760019312236
- 1.2057521100045385
- 1.183628218077836
- 1.1615043261511624
- 1.1393804342244636
- 1.1172565422977778
- 1.0951326503710939
- 1.0730087584444032
- 1.050884866517708
- 1.028760974591026
- 1.0066370826643358
- 0.984513190737649
- 0.9623892988109518
- 0.9402654068842736
- 0.918141514957577
- 0.8960176230308932
- 0.8738937311042024
- 0.8517698391775109
- 0.8296459472508266
- 0.8075220553241343
- 0.7853981633974483
- 0.7632742714707622
- 0.7411503795440699
- 0.7190264876173815
- 0.6969025956906983
- 0.674778703764
- 0.652654811837323
- 0.6305309199106229
- 0.6084070279839372
- 0.5862831360572538
- 0.5641592441305624
- 0.5420353522038658
- 0.5199114602771873
- 0.4977875683504934
- 0.4756636764238077
- 0.4535397844971188
- 0.4314158925704295
- 0.4092920006437368
- 0.38716810871706075
- 0.3650442167903582
- 0.34292032486367463
- 0.32079643293698623
- 0.29867254101029694
- 0.27654864908361027
- 0.25442475715691504
- 0.23230086523023172
- 0.21017697330354657
- 0.18805308137684976
- 0.16592918945017018
- 0.14380529752347446
- 0.12168140559678779
- 0.09955751367009578
- 0.077433621743414
- 0.055309729816719055
- 0.03318583789003433
curvature:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
- -4.415011037527593
